fieldLayouts:
  915128da-9087-4f70-a939-30a7b4a6a216:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c3994483-62e8-4edb-b9e7-128bbe9bd012
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6580fc11-bcf4-4080-a97b-01c688d7012f # Short Description
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48d94cf1-810f-44db-b8c5-644cf688b8c9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 891e2c26-4c9b-4a7e-8cf9-a7e3419f7432 # Carousel 2
            instructions: null
            label: Banner
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 779afe7f-0883-478d-ad86-b73b2b6c1d61
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c7810442-6833-4de5-99fc-1eee12ab1cde # Rich Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9fcaae10-4eb7-44ff-b86a-51e95f9c9c71
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 07cebb10-7e91-4d66-a6fc-94edbba90f29 # Carousel 1
            instructions: null
            label: 'About Image'
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d0f75fb-70dd-4957-9782-c2de34a173b8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 16fe91d6-b746-4a33-b27a-89a884e88d2c
        userCondition: null
handle: aboutUs
hasTitleField: true
name: 'About Us'
section: c710dda9-161e-4720-ab3c-ef508310a05b # About Us
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
