fieldLayouts:
  e77d80eb-c51d-49ca-9e4d-995d3bbd0bca:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 32f31894-7a31-4305-929d-60197abcf8ec
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: aa8454cc-0332-4ebe-9603-d4a3484708a0 # Page Title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 853d514d-331b-4309-9a87-93668de92ae6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 07cebb10-7e91-4d66-a6fc-94edbba90f29 # Carousel 1
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 920bf442-7c17-4d41-97e6-53bb5631f1e1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 93be5095-ea1f-4a41-a4ea-97892f0436ce
        userCondition: null
handle: contactUs
hasTitleField: true
name: 'Contact Us'
section: 21965bbe-a485-460b-bcd2-3cb57dfae29e # Contact Us
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
