fieldLayouts:
  076b1ba8-5c2d-45ef-9314-ff9038590342:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e42bd976-b06b-4c84-a4f8-f378e1ffcbfc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1035e9ec-c409-454a-9414-e50a9bab5e9d # Photos
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 855ad487-4061-4032-bab0-4c4ac69676ef
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6580fc11-bcf4-4080-a97b-01c688d7012f # Short Description
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 51a79624-d494-474a-894e-0828584ba5af
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c7810442-6833-4de5-99fc-1eee12ab1cde # Rich Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd7567e7-ec2a-4a79-8319-b87bff9ff538
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 01d82159-59cd-461e-aad5-c00aa78b6a3d # Service Title
            instructions: null
            label: Author
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4d6d8d6-d1ea-4ae9-9c76-822c55471eb4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 68de4abc-c63d-480b-a6f9-b92f5b455968
        userCondition: null
handle: newsBlog
hasTitleField: true
name: 'News Blog'
section: 171a5b1a-447a-4c4f-8446-61bb8deade78 # News Blog
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
