baseUrl: $PRIMARY_SITE_URL
handle: default
hasUrls: true
language: en-US
name: 'St. Edward Hospital, Dwinyama'
primary: true
siteGroup: 61374186-d744-4e86-8921-df9aed4a3a13 # St. Edward Hospital, Dwinyama
sortOrder: 1
