fieldLayouts:
  fdb0e942-3e45-40be-995d-61e1e4209085:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: f09ac0ba-06d2-4117-b3f2-02553e3deb45
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a357f0b5-5200-40b5-989e-6e256387b820
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
