columnSuffix: lusxbtau
contentColumnType: text
fieldGroup: 369ee378-e78c-45b5-96d7-2810c20427ef # Home Page
handle: carousel_2_Title
instructions: 'Carousel 2 Title'
name: 'Carousel 2 Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 1
  multiline: true
  placeholder: 'Carousel 2 Title'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
