columnSuffix: yisxdfsp
contentColumnType: string(1020)
fieldGroup: 98732b45-a75a-4682-b38f-68211a86d58e # Common
handle: location
instructions: null
name: Location
searchable: false
settings:
  byteLimit: null
  charLimit: 255
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: Location
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
