columnSuffix: bjofpuni
contentColumnType: string(400)
fieldGroup: 98732b45-a75a-4682-b38f-68211a86d58e # Common
handle: sendToEmail
instructions: 'Receive Email through this email'
name: 'Send to Email'
searchable: false
settings:
  byteLimit: null
  charLimit: 100
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
