columnSuffix: zioftqcr
contentColumnType: string(80)
fieldGroup: 98732b45-a75a-4682-b38f-68211a86d58e # Common
handle: telNumber
instructions: null
name: 'Tel Number'
searchable: false
settings:
  byteLimit: null
  charLimit: 20
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: 'Tel Number'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
