fieldLayouts:
  a2b940b5-770b-4c76-9538-3f15dd37747f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 093b96ce-f018-4a98-99c3-d6f8f1344404 # Location
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5406224-934c-41df-9231-2e90d76c08e0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9ee8328f-52de-43e8-adfe-d898c5b75943 # Email Address
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a270d23d-a3ae-4fd0-bb87-bf1e8f65953a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a25691bc-ec38-4d26-ac90-424df0a3f414 # Twitter Address
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9edbbf36-68c6-4fa1-a626-df75db10f7ff
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e1a794e8-76c2-40f8-9d0b-93588cac6e3f # Facebook Address
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e30ae398-2bb9-4c3d-87f8-fd9fc0c3a5e9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cb979a56-f588-4638-a2d8-33a4cd74d81f # Instagram Address
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb8a8083-7ac5-4f4c-8649-5105b074a9ab
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6d9f4e85-c20c-4bb7-a4ac-1291b563907b # Tel Number
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d2f6d0c-2d39-4238-811b-4d0031d69d4c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b65062c5-bc23-44c5-8088-439939e7dd6e # Send to Email
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9066e1df-f81e-47ed-8d43-ce862962544c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: aa8454cc-0332-4ebe-9603-d4a3484708a0 # Page Title
            instructions: null
            label: 'Top Bar Text'
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe01be2d-a366-47df-8f93-28b8e45decd0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 21889e6f-62c6-4fde-8096-d72b485514a6
        userCondition: null
handle: footer
name: Footer
sortOrder: 2
