defaultPlacement: end
enableVersioning: true
handle: layoutListing
name: 'Layout Listing'
propagationMethod: all
siteSettings:
  7eb80008-e9ae-442d-990e-2c8d122476cd: # St. Edward Hospital, Dwinyama
    enabledByDefault: true
    hasUrls: true
    template: _layout/app.twig
    uriFormat: _layout
type: channel
