defaultPlacement: end
enableVersioning: true
handle: servicesListing
name: 'Services Listing'
propagationMethod: all
siteSettings:
  7eb80008-e9ae-442d-990e-2c8d122476cd: # St. Edward Hospital, Dwinyama
    enabledByDefault: true
    hasUrls: true
    template: service/index
    uriFormat: service
type: single
